### ISSUE TITLE
Different labs solutions

### ISSUE THREAD

**Issue by AzizMaz7** [qiskit-community/ibm-quantum-challenge-spring-2023#9]
There can be multiple solutions for the exercises. Sometimes they are more efficient. 
I have solved the exercises using different logic/algorithms and many of them are efficient as well, I want to add these solutions to the solution folder in this repository. Please grant me permission to do that.
Thank you

Sincerely
AzizMaz7

**Comment by quantumAnsatz** [comment]
Not in charge but out of curiosity could you describe the more efficient solutions? Most ex solutions were often the most efficient.

**Comment by AzizMaz7** [comment]
Yes, but there can be different ways to solve a problem, eg. lab 4 ex2 and ex3, lab5 ex 1, ex 2, lab 3 ex 3 etc etc...

**Comment by quantumAnsatz** [comment]
However could you provide a representiative example? This could help the administrators to better accept your request. Lab 3 ex3 for example has no other solution, that is how the algorithm is carried out.

**Comment by AzizMaz7** [comment]
Like, eg: For lab4 ex2 you can use ccx gates instead of cx gates, lab5 ex1, and ex2 different ways to get the answer.
And yes for lab3 ex3 there is only one solution, that's my bad in the previous comment.

And I already pulled up a request where I submitted my codes so that they can verify it.

**Comment by quantumAnsatz** [comment]
Thanks for the details, these solutions do not seem optimal (ccx is harder to implement than cx, lab5 has a transpiled depth of almost 2000 > 54). Nevertheless, I hope the curators might find it interesting to allow for participant solutions for the challenges.

**Comment by kevinsung** [comment]
Thanks for your interest! The solutions we published are just examples, and we don't intend to publish any others here. Feel free to publish your solutions in your own personal repository.
